[package]
name = "samp_network_adapter"
version = "0.1.0"
authors = ["Rinat Namazov <rinat.namazov@rinwares.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3", features = ["memoryapi", "libloaderapi"] }
rust-ini = "0.19.0"
